# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
    # JDK version used for test coverage build
    coverageJDKVersion: 8

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macOS-latest, windows-latest]
        jdk: [ 8, 11 ]  # (open)JDK releases
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up openJDK version
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'zulu'  # =openJDK
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run:   |
        if [ "$RUNNER_OS" == "Linux" ]; then
              ./gradlew clean build jacocoTestReport
        elif [ "$RUNNER_OS" == "macOS" ]; then
              ./gradlew clean build jacocoTestReport
        elif [ "$RUNNER_OS" == "Windows" ]; then
              ./gradlew.bat clean build jacocoTestReport
        else
              echo "$RUNNER_OS not supported"
              exit 1
        fi
      shell: bash
  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up OpenJDK version ...
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu' 
        java-version: ${{ env.coverageJDKVersion }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle (JDK ${{ env.coverageJDKVersion }})
      run: ./gradlew clean check jacocoTestReport
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./build/reports/jacoco/test/jacocoTestReport.xml #optional